### ISSUE TITLE
Release 0.10.0 Cannot Store Spans

### ISSUE THREAD

**Issue by nickhudkins** [openzipkin/zipkin-gcp#114]
It appears that 0.10.0, when using (`/v1/spans/trace`) results in an io exception.

See below for full stacktrace. I can confirm that rolling back to 0.9.0 does not experience this failure.

```
2019-02-01 00:38:17.098 DEBUG 10 --- [ault-executor-3] llector$$EnhancerBySpringCGLIB$$71113940 : Cannot store spans [860477f68d6feb30/4d62310801995e51, 860477f68d6feb30/6ede436457821dff, 860477f68d6feb30/ce181a15cbcac3ea, ...] due to StatusRuntimeException(UNAVAILABLE: io exception)

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:530) ~[grpc-core-1.18.0.jar!/:1.18.0]
	at zipkin2.reporter.stackdriver.internal.CallbackToUnaryClientCallListener.onClose(CallbackToUnaryClientCallListener.java:57) [zipkin-sender-stackdriver-0.10.0.jar!/:?]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.18.0.jar!/:1.18.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.18.0.jar!/:1.18.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedSocketException: Network unreachable: cloudtrace.googleapis.com/2607:f8b0:400c:c06:0:0:0:5f:443
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:454) ~[?:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:446) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[?:1.8.0_191]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:312) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1366) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.connect(SslHandler.java:716) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.connect(ProtocolNegotiators.java:498) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:38) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:535) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	... 1 more
Caused by: java.net.SocketException: Network unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:454) ~[?:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:446) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[?:1.8.0_191]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:312) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1366) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.connect(SslHandler.java:716) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.connect(ProtocolNegotiators.java:498) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:38) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:535) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.18.0.jar!/:1.18.0]
	... 1 more
```

**Comment by anuraaga** [comment]
FWIW, I am using 0.10.0 now without problem. The error message also seems like it would affect both versions as both 0.9.0 and 0.10.0 use cloudtrace.googleapis.com, just with different endpoints. Does your network have any proxy or such that would be affected by the client's endpoint URL path changing?

**Comment by nickhudkins** [comment]
@anuraaga 	I am not sure if there is a difference between `/v1/spans/trace` and `/v2/spans/trace`.

Are you saying that from 0.9.0 -> 0.10.0, the trace client endpoint URL path changed?

In the trace I am seeing the following as the endpoint it is trying to hit, and it may be my own ignorance, but that is not a host / domain format that is familiar to me.
`cloudtrace.googleapis.com/2607:f8b0:400c:c06:0:0:0:5f:443`

**Comment by anuraaga** [comment]
Netty's error message often concatenates host and IP - I had the same reaction when I saw it too though. It's not the same but a similar issue for reference is https://github.com/line/armeria/issues/1146

To clarify, the major change in this release is accessing cloudtrace.googleapis.com/google.devtools.cloudtrace.v2.TraceService instead of the same but v1. I don't think it's likely related to your error though but have no ideas to debug ><

**Comment by adriancole** [comment]
troubleshooting is hard to keep as an open issue with people simultaneously working and not working, especially on a SaaS product as there could be many reasons.

I would recommend asking google if they have any access logs to determine what's the matter. Meanwhile we can just update versions on a next release as there is nothing to go on here.

Note as late as last night others are working. There may or may not be an issue with their server imp, which means you could possibly want to report these concerns to google before they disable the v1 endpoint.

I'm closing this for now as there is no action we can take, but you can feel free to jump back on gitter. If we find anything we can change in the code, we can open an issue about it https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
fyi @mtwo we are getting spurious complaints about v2 api. here's another

**Comment by adriancole** [comment]
@nickhudkins I have cut 0.10.1 just in case latest versions of things fix this. can you please try just in case?

**Comment by adriancole** [comment]
here is one reason a version update could work. If you are using the docker image, the patch updates the ssl library needed for stackdriver to work. this could explain spurious behavior with docker and not if someone isn't using docker.

https://github.com/openzipkin/docker-zipkin-gcp/commit/360a8ec6d464a10e6d2d645f6dab2bccfc7e0763#diff-3254677a7917c6c01f55212f86c57fbfR24

**Comment by mtwo** [comment]
@adriancole I've passed it on to the team
