### ISSUE TITLE
Google Stackdriver Trace drops spans without name

### ISSUE THREAD

**Issue by TYsewyn** [openzipkin/zipkin-gcp#123]
When enabling debug logging for the `zipkin2` package when using Spring Cloud Sleuth (Greenwich.SR1) we get following error:
```
Dropped 18 spans due to StatusRuntimeException(INVALID_ARGUMENT: TraceSpan.name for TraceSpan.span_id 1829621750604935860 cannot be empty.)
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: TraceSpan.name for TraceSpan.span_id 1829621750604935860 cannot be empty.
at io.grpc.Status.asRuntimeException(Status.java:526)
at zipkin2.reporter.stackdriver.internal.AwaitableUnaryClientCallListener.onClose(AwaitableUnaryClientCallListener.java:96)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

This should be handled more gracefully and not dropping all queued spans.

Relates to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1337

**Comment by adriancole** [comment]
as far as I can tell, this is a remote server exception.. meaning that stackdriver is enforcing this on their side.

To patch, today you could add a bean for brave's FinishedSpanHandler to add the name "unknown" when the span name is absent. Might also be helpful to find what data is causing empty span names.

We need feedback from stackdriver folks about if they can tolerate spans missing names. cc @mtwo

**Comment by adriancole** [comment]
ex.

```java
@Bean FinishedSpanHandler forceNonEmptyNameForStackdriver() {
  return new FinishedSpanHandler() {
      @Override public boolean handle(TraceContext context, MutableSpan span) {
        if (span.name() == null) span.name("unknown");
        return true; // don't drop the span
      }
  };
}
```

A PR could also be accepted here to change the converter to coerce null to "unknown", but you would need to upgrade into that.

**Comment by mtwo** [comment]
I'm pretty sure that the API intentionally doesn't allow unnamed spans ... will follow up with the right people but I suspect that you'll just want to use the workaround that @adriancole proposed.

**Comment by saturnism** [comment]
@TYsewyn btw, was this via spring-cloud-gcp trace, or was this happening from zipkin server to stackdriver?

**Comment by TYsewyn** [comment]
@saturnism if I remember correctly it was an application that was pushing to both Stackdriver and Zipkin at the same time. Traces/spans were being received by the Zipkin server, but we didn't see those traces appear in Stackdriver. After enabling debug logging we saw these stacktraces.

**Comment by shakuzen** [comment]
@TYsewyn were you able to track down what instrumentation was making the nameless spans? We'd want to fix that also.

**Comment by TYsewyn** [comment]
@shakuzen The spans were created by Spring Cloud Sleuth, and in our case specifically the `TracingChannelInterceptor`. We ended up using the proposed workaround.
From the related issue at Spring Cloud Sleuth:

> A first quick check is pointing to the following:
> 
> `TracingChannelInterceptor`, where the `beforeHandle` method is starting a consumer span without a name.
> `TraceLoadBalancerFeignClient`, where the started `fallbackSpan` in the execute method doesn't have a name.
> `MonoWebFilterTrace`, where a new child span is started without a name if there was already one in the context.

**Comment by saturnism** [comment]
@TYsewyn it sounds like we should fix this in the server ride then, right?
